### ISSUE TITLE
doesn't work 

### ISSUE THREAD

**Issue by cn0xroot** [tedyapo/mw-voice-marker#6]
hi, @tedyapo ,nice project.
i find your post on hackaday https://hackaday.io/project/21145-am-band-voice-frequency-marker/log/145487-osmo-fl2k-ftw

but when i do as you say,something error:

```
./make_fl2k_file.py eu_order0_8192k.dat -b 531 -e 1602 -s 9 -o 0 -c 4096000 -r 8192000
voices generated                  
Traceback (most recent call last):
  File "./make_fl2k_file.py", line 193, in <module>
    main()
  File "./make_fl2k_file.py", line 189, in main
    f_output_sample=args.output_sample)
  File "./make_fl2k_file.py", line 113, in generate_voice_marker
    a_s = signal.resample_poly(a, f_carrier_sample, f_speech)
AttributeError: 'module' object has no attribute 'resample_poly'
```

do you know how to fix it?

**Comment by tedyapo** [comment]
My suspicion is that you are using an old version of scipy which does not have the signal.resample_poly() function.  To get the code working immediately, you can change this call to signal.resample(), although it may run more slowly.

A better solution is to update to a more recent version of scipy.

I will add instructions to the readme for installing numpy and scipy in a virtualenv environment.

**Comment by tedyapo** [comment]
I updated the readme with instructions on installing newer versions of numpy and scipy into a python virtualenv.  Please try this and see if it resolves your issue.

**Comment by cn0xroot** [comment]
thank you so much.
i'll try it again

**Comment by tedyapo** [comment]
Were you able to get the code working?

**Comment by cn0xroot** [comment]
yes,it work now.thank you so much!
